language: objective-c
osx_image: xcode10.1
script:
    - xcodebuild -project TransitTimes.xcodeproj -scheme TransitTimes -destination 'platform=iOS Simulator,OS=12.1,name=iPhone XS' -configuration Debug build test
